distributor:
  routes:
    b1784d60-111f-4053-94e3-0962ddf24efa:
      uuid: b1784d60-111f-4053-94e3-0962ddf24efa
      weight: 10000
      value:
        type: mail
        pass: ''
        config:
          mail:
            enabled: true
            async: inherit
            disableStorage: inherit
            enableDataProviders:
              type: all
              config:
                all: {}
            gate:
              type: 'true'
              config:
                'true': {}
            data:
              passthroughFields:
                enabled: true
              fieldMap:
                fields: {}
              ignoreEmptyFields:
                enabled: true
              excludeFields:
                fields: {}
              prefix:
                prefix: ''
                action: add
            subject:
              data:
                type: constant
                config:
                  constant:
                    value: 'New Form Submission'
              modifiers: {}
            sender:
              data:
                type: email
                config:
                  email:
                    address:
                      data:
                        type: constant
                        config:
                          constant:
                            value: ''
                      modifiers: {}
                    name:
                      data:
                        type: constant
                        config:
                          constant:
                            value: ''
                      modifiers: {}
              modifiers: {}
            recipients:
              data:
                type: email
                config:
                  email:
                    address:
                      data:
                        type: constant
                        config:
                          constant:
                            value: ''
                      modifiers: {}
                    name:
                      data:
                        type: constant
                        config:
                          constant:
                            value: ''
                      modifiers: {}
              modifiers: {}
            replyTo:
              data:
                type: email
                config:
                  email:
                    address:
                      data:
                        type: constant
                        config:
                          constant:
                            value: ''
                      modifiers: {}
                    name:
                      data:
                        type: constant
                        config:
                          constant:
                            value: ''
                      modifiers: {}
              modifiers: {}
            includeAttachmentsInMail: false
            plainTextTemplate:
              template: '{% for key,value in all_values %}\n{{ key }}: {{ value }}\n{% endfor %}'
            useHtml: true
            htmlTemplate:
              template: "<table>\n  <tr>\n    <td>Key</td>\n    <td>Value</td>\n  </tr>\n  {% for key,value in all_values %}\n    <tr>\n      <td>{{ key }}</td>\n      <td>{{ value }}</td>\n    </tr>\n  {% endfor %}\n</table>"
metaData:
  name: 'Mail Route with Twig Template'
  version:
    core: 1.0.0
    distributor-core: 1.0.0
    distributor-mail: 1.0.0
    template-engine-twig: 1.0.0
  includes: {}
